apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: petclinic
type: Opaque
data:
  MYSQL_USER: cGV0Y2xpbmk=  # base64 for "petclinic"
  MYSQL_PASS: cGV0Y2xpbmk=  # base64 for "petclinic"
